"""
BasePurpose — abstract base class for all TTT Purposes.

Consuming projects subclass BasePurpose and implement _handle_event().
The public dispatch entry point (take_turn()) is owned by this base class
and must not be overridden — it validates the hub token before delegating
to _handle_event().

The hub assigns a token to each Purpose at registration time via
TTT.register_purpose(). Until registered, the Purpose is unbound and
take_turn() will raise UnboundPurposeError. After registration, only
HubEvents carrying the matching token are accepted — any other call to
take_turn() raises UnauthorizedDispatchError.

This design closes the point-to-point bypass: because take_turn() validates
the token, a Purpose cannot receive events from any source other than the
hub that registered it. Purposes that want to trigger work on other Purposes
must propose a Delta; the hub decides what happens next.

Subclass contract:
  - Implement _handle_event(event) for domain logic.
  - Do not override take_turn().
  - Pass name and id to super().__init__() or set them as class attributes.
  - Do not set _token directly — it is assigned exclusively by the hub.
"""

from __future__ import annotations

import abc
from uuid import UUID

from .errors import UnauthorizedDispatchError, UnboundPurposeError
from .events import HubEvent

# Sentinel used to distinguish "not yet registered" from any real token value.
_UNBOUND = object()


class BasePurpose(abc.ABC):
    """
    Abstract base class for TTT Purposes.

    Implements the TurnTakerProtocol / PurposeProtocol contract with hub
    token validation built in. Subclasses implement _handle_event() for
    domain logic and must not override take_turn().

    Attributes:
        name: Semantic kind of this Purpose (e.g. "ca", "socratic").
            Determines the observation namespace this Purpose writes into.
            Multiple instances may share the same name; id distinguishes them.
        id: Per-instance UUID. Assigned by the subclass or its factory.

    The token attribute is intentionally absent from __init__ — it is
    assigned exclusively by TTT.register_purpose() and must not be set
    directly by subclasses or consuming code.
    """

    name: str
    id: UUID

    def __init__(self) -> None:
        """
        Initialise the base Purpose in unbound state.

        Subclasses must set self.name and self.id (as instance or class
        attributes) before or after calling super().__init__(). The token
        is not set here — it is assigned by the hub at registration time.
        """
        self._token: object = _UNBOUND

    @property
    def token(self) -> str | None:
        """
        The hub-assigned token for this Purpose instance.

        None until registered with a hub. After registration, always a
        non-empty string. Never set this directly — use TTT.register_purpose().
        """
        if self._token is _UNBOUND:
            return None
        return self._token  # type: ignore[return-value]

    def _assign_token(self, token: str) -> None:
        """
        Assign the hub token. Called exclusively by TTT.register_purpose().

        Not part of the public API. Consuming code must never call this
        directly — doing so would allow a Purpose to accept events from
        an arbitrary source rather than only from the registering hub.

        Args:
            token: Non-empty string token generated by the hub.
        """
        if not token:
            raise ValueError("hub token must be a non-empty string")
        self._token = token

    async def take_turn(self, event: HubEvent) -> None:
        """
        Validate the hub token and delegate to _handle_event().

        This is the hub-facing dispatch entry point. It must not be
        overridden by subclasses — override _handle_event() instead.

        Validates that:
          1. This Purpose has been registered with a hub (token is bound).
          2. The event carries a token that matches this Purpose's token.

        These checks close the point-to-point bypass: a Purpose cannot
        receive events from any caller other than the hub that registered
        it, because no other caller has the matching token.

        Args:
            event: The HubEvent to process.

        Raises:
            UnboundPurposeError: If this Purpose has not been registered
                with a hub (token not yet assigned).
            UnauthorizedDispatchError: If event.hub_token does not match
                this Purpose's assigned token.
        """
        if self._token is _UNBOUND:
            raise UnboundPurposeError(
                f"Purpose {self.name!r} (id={self.id}) has not been registered "
                f"with a hub. Call TTT.register_purpose() before dispatch."
            )
        if event.hub_token != self._token:
            raise UnauthorizedDispatchError(
                f"Purpose {self.name!r} (id={self.id}) rejected event "
                f"{event.event_id} — hub token mismatch. "
                f"Purposes must receive events only from the hub that registered them."
            )
        await self._handle_event(event)

    @abc.abstractmethod
    async def _handle_event(self, event: HubEvent) -> None:
        """
        Handle a validated HubEvent. Implement domain logic here.

        Called by take_turn() after token validation passes. The event
        is guaranteed to originate from the hub that registered this Purpose.

        Subclasses may propose Deltas back to the hub, update internal
        state, or take any other action appropriate to their domain.
        They must not call take_turn() on other Purposes directly.

        Args:
            event: The validated HubEvent to handle.
        """
