"""
turnturnturn/dataclasses.py
conversational turn processing middleware — core data model

Version: 0.2

Changes from v0.1:
  - turn_id uses secrets.token_hex(12) — 24 hex chars
  - timestamp None-checks use `is None` pattern (not `or default`) throughout
  - DAGNode: proper status state machine; is_eligible checks status == "eligible"
  - CTO.to_dict() and Delta.to_dict() stub serialization methods
  - payload helpers include _schema and _v fields by convention
  - EventType: TURN_ANNOTATED added (annotation event, out-of-band write)
"""

from __future__ import annotations

import secrets
import time
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Mapping


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class EventType(str, Enum):
    # --- pipeline events (DAG nodes) ---
    TURN_RECEIVED     = "turn_received"
    DELTA_MERGED      = "delta_merged"
    PURPOSE_FIRED     = "purpose_fired"
    PURPOSE_COMPLETE  = "purpose_complete"

    # --- annotation events (out-of-band writes) ---
    TURN_OBSERVATION_RECORDED = "turn_observation_recorded"


class DAGStatus(str, Enum):
    """
    State machine for DAGNode processing status.
    Hub drives all transitions; DAGNode.is_eligible reflects current state.

    Transitions:
        waiting    → eligible    (hub: all deps resolved)
        eligible   → dispatched  (hub: Purpose fired)
        dispatched → resolved    (hub: purpose_complete received)
    """
    WAITING    = "waiting"
    ELIGIBLE   = "eligible"
    DISPATCHED = "dispatched"
    RESOLVED   = "resolved"


# ---------------------------------------------------------------------------
# Observations
# ---------------------------------------------------------------------------


@dataclass
class Observation:
    """
    A single annotated observation attached to a CTO.

    owner: purpose namespace that produced this observation (e.g. "ue_detector").
    shared: flag indicating where the data lives.
            * **False** – written into the owner's private namespace; only the
              owner may modify or read the value. Nothing in a private
              namespace is visible to other purposes.
            * **True** – written into the *shared* namespace. In the shared
              namespace every key maps to a **list**; when a purpose appends a
              value it is added to the list (`[a]` → `[a, b]`). All purposes
              may append to and read shared entries. The hub enforces the list
              semantics.
    value: arbitrary purpose-defined content. For non‑shared observations the
           value is stored directly; for shared observations the value is
           appended to a list. In either case the data must be JSON-serializable
           (dicts, lists, strings, numbers, bools, None). The hub does not
           validate this at runtime; purposes are responsible.
    """
    owner:  str
    shared: bool
    value:  Any


# ---------------------------------------------------------------------------
# Canonical Turn Object
# ---------------------------------------------------------------------------


@dataclass
class CTO:
    """
    Canonical Turn Object — the primary unit of per-turn state.

    turn_id: 24-char hex identifier, unique per turn. Generated by the hub;
              never reused. Used as the stable key for DAG lookups and session
              log records.
    timestamp: Unix float at turn creation. Set by the hub at CTO construction.
    text: the raw turn text as received from the participant.
    role: participant role identifier (e.g. "subject", "interviewer").
    observations: keyed by purpose namespace. Each value is either a
                  single Observation (private namespace) or, for shared data,
                  a list of Observation values representing the shared list
                  semantics described above.
                  Access pattern: `cto.observations["purpose_name"]` or, when
                  iterating shared entries, walk the list.
    ext: purpose-specific extension data. Namespaced by purpose. Purposes
         may write arbitrary data here; other purposes should treat foreign
         namespaces as opaque. Intended for lightweight per-turn metadata
         that doesn't warrant a full Observation.
    """
    turn_id: str
    timestamp:    float
    text:         str
    role:         str
    observations: dict[str, list[Observation]] = field(default_factory=dict)

    @classmethod
    def create(cls, text: str, role: str, timestamp: float | None = None) -> "CTO":
        """
        Factory method. Hub uses this to construct all CTOs.
        Generates turn_id and sets timestamp if not supplied.
        """
        return cls(
            turn_id=secrets.token_hex(12),
            timestamp=time.time() if timestamp is None else timestamp,
            text=text,
            role=role,
        )

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize to a JSON-safe dict for persistence and transport.
        Observations are expanded inline; ext is passed through as-is.
        Purposes are responsible for ensuring ext values are JSON-safe.
        """
        return {
            "turn_id":  self.turn_id,
            "timestamp": self.timestamp,
            "text":      self.text,
            "role":      self.role,
            "observations": {
                k: {"owner": v.owner, "shared": v.shared, "value": v.value}
                for k, v in self.observations.items()
            },
            "ext": self.ext,
        }


# ---------------------------------------------------------------------------
# Delta
# ---------------------------------------------------------------------------


@dataclass
class Delta:
    """
    A mutation record produced by a purpose after processing a CTO.

    source_turn_id: turn_id of the CTO this delta was derived from.
    purpose_id:      identifier of the purpose that produced this delta.
    kind:            purpose-defined mutation kind (e.g. "observation_added",
                     "flag_raised", "annotation_applied").
    payload:         the mutation content. Must be JSON-safe. By convention,
                     all payloads include _schema (payload format identifier)
                     and _v (version int). Use payload helpers below.
    timestamp:       Unix float at delta creation.
    """
    source_turn_id: str
    purpose_id: str
    invocation_id: str | None = None  # hub-generated per dispatch (optional)
    kind:            str
    payload:         dict[str, Any]
    timestamp:       float = field(default_factory=time.time)

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize to a JSON-safe dict.
        payload is expected to be JSON-safe by construction (see payload helpers).
        """
        # legacy "provider" field has been retired; the delta now carries
        # purpose_id (and invocation_id) exclusively.
        result = {
            "source_turn_id": self.source_turn_id,
            "purpose_id":       self.purpose_id,
            "kind":            self.kind,
            "payload":         self.payload,
            "timestamp":       self.timestamp,
        }
        if self.invocation_id is not None:
            result["invocation_id"] = self.invocation_id
        return result


# ---------------------------------------------------------------------------
# DAG node
# ---------------------------------------------------------------------------


@dataclass
class DAGNode:
    """
    Represents a single unit of work in the purpose processing DAG.

    node_id:   stable identifier for this node type (e.g. "ue_detector").
    deps:      set of node_ids that must be resolved before this node is eligible.
    status:    current processing state. See DAGStatus for valid transitions.
               The hub drives all status transitions; nodes do not self-transition.

    is_eligible: True iff status == DAGStatus.ELIGIBLE.
                 Hub checks this before dispatching a Purpose.
    """
    node_id: str
    deps:    set[str]   = field(default_factory=set)
    status:  DAGStatus  = DAGStatus.WAITING

    @property
    def is_eligible(self) -> bool:
        return self.status == DAGStatus.ELIGIBLE


# ---------------------------------------------------------------------------
# Purpose
# ---------------------------------------------------------------------------


@dataclass
class Purpose:
    """
    A unit of deferred work dispatched by the hub.

    purpose_id:    24-char hex identifier. Generated by the hub at dispatch time.
    node_id:       the DAGNode this Purpose was generated for.
    cto:           the CTO to be processed.
    dispatched_at: Unix float at dispatch.
    """
    purpose_id:    str
    invocation_id: str | None = None  # hub-generated per dispatch (optional)
    node_id:       str
    cto:           CTO
    dispatched_at: float

    @classmethod
    def create(cls, node_id: str, cto: CTO, dispatched_at: float | None = None) -> "Purpose":
        return cls(
            purpose_id=secrets.token_hex(12),
            node_id=node_id,
            cto=cto,
            dispatched_at=time.time() if dispatched_at is None else dispatched_at,
        )


# ---------------------------------------------------------------------------
# Hub event
# ---------------------------------------------------------------------------


@dataclass
class HubEvent:
    """
    An event record emitted by the hub on each state transition.

    event_id:   24-char hex identifier.
    event_type: EventType value.
    turn_id:   turn_id of the CTO associated with this event, if any.
    payload:    event-specific data. By convention, includes _schema and _v.
    timestamp:  Unix float at event emission.
    """
    event_id:   str
    event_type: EventType
    turn_id: str | None
    payload:    dict[str, Any]
    timestamp:  float

    @classmethod
    def create(
        cls,
        event_type: EventType,
        turn_id: str | None = None,
        payload: dict[str, Any] | None = None,
        timestamp: float | None = None,
    ) -> "HubEvent":
        return cls(
            event_id=secrets.token_hex(12),
            event_type=event_type,
            turn_id=turn_id,
            payload=payload if payload is not None else {},
            timestamp=time.time() if timestamp is None else timestamp,
        )


# ---------------------------------------------------------------------------
# Payload helpers
#
# Convention: all payloads include _schema (str identifier for the payload
# format) and _v (int version). This makes debugging and future migrations
# significantly easier. Use these helpers to build payloads; do not construct
# payload dicts manually in hub.py or purpose code.
# ---------------------------------------------------------------------------


def payload_turn_received(turn_id: str, role: str) -> dict[str, Any]:
    return {
        "_schema": "turn_received",
        "_v":      1,
        "turn_id": turn_id,
        "role":     role,
    }



def payload_purpose_fired(
    purpose_id: str,
    node_id: str,
    turn_id: str,
) -> dict[str, Any]:
    return {
        "_schema":    "purpose_fired",
        "_v":         1,
        "purpose_id": purpose_id,
        "node_id":    node_id,
        "turn_id":   turn_id,
    }


def payload_purpose_complete(
    purpose_id: str,
    node_id: str,
    turn_id: str,
) -> dict[str, Any]:
    return {
        "_schema":    "purpose_complete",
        "_v":         1,
        "purpose_id": purpose_id,
        "node_id":    node_id,
        "turn_id":   turn_id,
    }


def turn_observation_recorded(
    turn_id: str,
    purpose_id: str,
    observation_key: str,
) -> dict[str, Any]:
    """
    Payload for TURN_OBSERVATION_RECORDED events (out-of-band observation writes).
    observation_key identifies which observations entry was written.
    """
    return {
        "_schema":         "turn_observation_recorded",
        "_v":              1,
        "turn_id":        turn_id,
        "purpose_id":      purpose_id,
        "observation_key": observation_key,
    }
